
05.Jul 2020 17:15:00 error at loading model hyperparameters
[Errno 2] No such file or directory: './0.1_hyperparameters/model_hyperparameters.json'
Traceback (most recent call last):
  File ".\_2_train.py", line 94, in train
    with open(''.join([local_script_settings['hyperparameters_path'], 'model_hyperparameters.json'])) \
FileNotFoundError: [Errno 2] No such file or directory: './0.1_hyperparameters/model_hyperparameters.json'

05.Jul 2020 17:27:06 correct model training, correct saving of model and weights

05.Jul 2020 17:27:06 settings modified and saved

05.Jul 2020 17:27:44 correct model training, correct saving of model and weights

05.Jul 2020 17:27:44 settings modified and saved

05.Jul 2020 17:29:10 correct model training, correct saving of model and weights

05.Jul 2020 17:29:10 settings modified and saved

05.Jul 2020 18:16:34 correct model training, correct saving of model and weights

05.Jul 2020 18:16:34 settings modified and saved

05.Jul 2020 18:16:51 correct model training, correct saving of model and weights

05.Jul 2020 18:16:51 settings modified and saved

05.Jul 2020 18:17:15 correct model training, correct saving of model and weights

05.Jul 2020 18:17:15 settings modified and saved

05.Jul 2020 18:18:04 correct model training, correct saving of model and weights

05.Jul 2020 18:18:04 settings modified and saved

05.Jul 2020 18:18:39 correct model training, correct saving of model and weights

05.Jul 2020 18:18:39 settings modified and saved

07.Jul 2020 10:48:52 model training error
name 'image_normalizer' is not defined
Traceback (most recent call last):
  File ".\_2_train.py", line 145, in train
    normalizer = image_normalizer()
NameError: name 'image_normalizer' is not defined

07.Jul 2020 20:02:37 model training error
normalize() missing 1 required positional argument: 'local_image'
Traceback (most recent call last):
  File ".\_2_train.py", line 149, in train
    preprocessing_function=normalizer.normalize(),
TypeError: normalize() missing 1 required positional argument: 'local_image'

07.Jul 2020 20:04:43 model training error
normalize() missing 1 required positional argument: 'local_image'
Traceback (most recent call last):
  File ".\_2_train.py", line 149, in train
    preprocessing_function=normalizer.normalize(),
TypeError: normalize() missing 1 required positional argument: 'local_image'

07.Jul 2020 20:05:33 model training error
normalize() missing 1 required positional argument: 'local_image'
Traceback (most recent call last):
  File ".\_2_train.py", line 149, in train
    preprocessing_function=normalizer.normalize(),
TypeError: normalize() missing 1 required positional argument: 'local_image'

07.Jul 2020 20:09:47 model training error
normalize() missing 1 required positional argument: 'local_image'
Traceback (most recent call last):
  File ".\_2_train.py", line 149, in train
    preprocessing_function=normalizer.normalize(),
TypeError: normalize() missing 1 required positional argument: 'local_image'

07.Jul 2020 20:24:53 model training error
normalize() missing 1 required positional argument: 'local_image'
Traceback (most recent call last):
  File ".\_2_train.py", line 149, in train
    preprocessing_function=normalizer.normalize(),
TypeError: normalize() missing 1 required positional argument: 'local_image'
